		<html>
<head>
<!--script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'/-->
</head>
</html>
<?php
//include "testsms.php";
 
		
 
	if(isset($_POST['Submit'])){ 

     
	 
      if(empty($errors)==true){
       //  move_uploaded_file($file_tmp,"images/".$file_name);
        // echo "Success";
		
        $subject = " Rushforme";

        //$sendTo = "helpdesk@yottabytetechnologies.com";
		$to = "parijatak43@gmail.com";
		$headers = "CC: prajakta.gitte23@gmail.com";
        
        //$ServiceNeeded = ":".$_POST['request']."\r\n";
        
           $message = '
		   
		   <html>
		   <head>
				
			</head>
			<body>
				<table width="500" border="1" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC">
				
				<tr>
					<td><table width="500" border="0" cellspacing="0" cellpadding="8">
					<tr>
				
					<td  bgcolor="#CDD9F5"><strong>name:</strong></td><td bgcolor="#CDD9F5">'.$_REQUEST['name'].'</strong></td></tr>
						
         
			<tr><td>number: </td><td>'.$_REQUEST['number'].'</td></tr>
         
        <tr><td>Experience: </td><td>'.$_REQUEST['address'].'</td></tr>
             
         <tr><td>address: </td><td>'.$_REQUEST['email'].'</td></tr>

         <tr><td>message: </td><td>'.$_REQUEST['message'].'</td></tr>
         
          
		 </tr>
		 </table>
		 </body>
		 </html>' ;
		 


$from = "Rushforme.com: admin@rushforme.com";
//$from = "From:".$_POST["email"];
$subject = "Carreer Information";

$separator = md5(time());

// carriage return type (we use a PHP end of line constant)
$eol = PHP_EOL;

// attachment name

//$pdfdoc is PDF generated by FPDF
//$attachment = $content;

// main header
$headers  = "From: ".$from.$eol;
$headers .= 'Cc: prajakta.gitte23@gmail.com' . "\r\n";
$headers .= "MIME-Version: 1.0".$eol; 
$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

// no more headers after this, we start the body! //

$body = "--".$separator.$eol;
$body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
$body .= " Partner Details: ".$eol;

// message
$body .= "--".$separator.$eol;
$body .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
$body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
$body .= $message.$eol;



// send message
if (mail($to, $subject, $body, $headers)) {
  
  				

  
	header("location:http://rushforme.com/partner.php");


   
   
} else {
    echo "mail not sent ... ERROR";
}


				
	  }
	 }




?>





	<!--?php

if(isset($_POST["Submit"])){
//Checking for blank Fields..
if($_POST["name"]==""||$_POST["number"]==""||$_POST["email"]==""||$_POST["address"]==""||$_POST["message"]==""){
echo "Fill All Fields..";
}else{
// Check if the "Sender's Email" input field is filled out
$email=$_POST['email']; 
 
 // Sanitize e-mail address
 $email =filter_var($email, FILTER_SANITIZE_EMAIL);
 
 // Validate e-mail address
 $email= filter_var($email, FILTER_VALIDATE_EMAIL);

 if (!$email){
echo "Invalid Sender's Email";
 }
 else{
 $subject = "Partner With Us";
 

 $message = '
		     
		 
		    name:"'.$_REQUEST['name'].'"
				
			number:"'.$_REQUEST['number'].'"
         
            email: "'.$_REQUEST['email'].'"
             
            address: "'.$_REQUEST['address'].'"

            message: "'.$_REQUEST['message'].'"
';
         

 $headers = 'From:admin@rushforme.com'. $email2 . "\r\n"; // Sender's Email
 $headers .= 'Cc:parijatak43@gmail.com'. $email2 . "\r\n"; // Carbon copy to Sender
 

 // message lines should not exceed 70 characters (PHP rule), so wrap it
 $message = wordwrap($message, 70);
 
 

 // Send mail by PHP Mail Function
 mail("recievers_mail_id@xyz.com", $subject, $message, $headers);
 header("location:http://rushforme.com/partner.php");
 echo "Your mail has been sent successfuly ! Thank you for your feedback";
 }
}
}
?-->