		<html>
<head>
<!--script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'/-->
</head>
</html>
<?php
//include "testsms.php";
 
		
 
	if(isset($_POST['Submit'])){ 

     if(isset($_FILES['fileToUpload'])){
      $errors= array();
      $filename = $_FILES['fileToUpload']['name'];
      $file_size =$_FILES['fileToUpload']['size'];
      $file_tmp =$_FILES['fileToUpload']['tmp_name'];
      $file_type=$_FILES['fileToUpload']['type'];
      $file_ext=strtolower(end(explode('.',$_FILES['fileToUpload']['name'])));
      
      $file = $file_tmp;
	  //$filename = 'cpanel.txt';
 //$file = $_SERVER['DOCUMENT_ROOT']."/mail/".$filename;
$content = file_get_contents( $file);
$content = chunk_split(base64_encode($content));
$uid = md5(uniqid(time()));
$name = basename($file);
      
      /*$expensions= array("jpeg","jpg","png");
      
      if(in_array($file_ext,$expensions)=== false){
         $errors[]="extension not allowed, please choose a JPEG or PNG file.";
      }      */
      
      if($file_size > 6291456){
         $errors[]='File size must be exactly 6 MB';
      }
       
	   
	   
	 
      if(empty($errors)==true){
       //  move_uploaded_file($file_tmp,"images/".$file_name);
        // echo "Success";
		
        $subject = " Rushforme";

        //$sendTo = "helpdesk@yottabytetechnologies.com";
		$to = "parijatak43@gmail.com";
		$headers = "CC: prajakta.gitte23@gmail.com";
        
        //$ServiceNeeded = ":".$_POST['request']."\r\n";
        
           $message = '
		   
		   <html>
		   <head>
				
			</head>
			<body>
				<table width="500" border="1" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC">
				
				<tr>
					<td><table width="500" border="0" cellspacing="0" cellpadding="8">
					<tr>
				
					<td  bgcolor="#CDD9F5"><strong>Candidate name:</strong></td><td bgcolor="#CDD9F5">'.$_REQUEST['cname'].'</strong></td></tr>
						
         
			<tr><td>Candidate phone number: </td><td>'.$_REQUEST['cnumber'].'</td></tr>
         
        <tr><td>Experience: </td><td>'.$_REQUEST['experience'].'</td></tr>
             
         <tr><td>Candidate email: </td><td>'.$_REQUEST['cemail'].'</td></tr>

         <tr><td>Candidate Current Working company: </td><td>'.$_REQUEST['company'].'</td></tr>
         
          
		 </tr>
		 </table>
		 </body>
		 </html>' ;
		 


$from = "Rushforme.com: admin@rushforme.com";
//$from = "From:".$_POST["email"];
$subject = "Carreer Information";

$separator = md5(time());

// carriage return type (we use a PHP end of line constant)
$eol = PHP_EOL;

// attachment name

//$pdfdoc is PDF generated by FPDF
$attachment = $content;

// main header
$headers  = "From: ".$from.$eol;
$headers .= 'Cc: prajakta.gitte23@gmail.com' . "\r\n";
$headers .= "MIME-Version: 1.0".$eol; 
$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

// no more headers after this, we start the body! //

$body = "--".$separator.$eol;
$body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
$body .= " Candidate information: ".$eol;

// message
$body .= "--".$separator.$eol;
$body .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
$body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
$body .= $message.$eol;

// attachment
$body .= "--".$separator.$eol;
$body .= "Content-Type: application/octet-stream; name=\"".$filename."\"".$eol; 
$body .= "Content-Transfer-Encoding: base64".$eol;
$body .= "Content-Disposition: attachment".$eol.$eol;
$body .= $attachment.$eol;
$body .= "--".$separator."--";

// send message
if (mail($to, $subject, $body, $headers)) {
  
  				
echo "<script>$(document).ready(function(){
	
	
	});</script>";
  
	header("location:http://rushforme.com/career.php");


   
   
} else {
    echo "mail not sent ... ERROR";
}


				
	  }
	 }


}

?>

<!--<tr><td>employee</td><td>'.$_REQUEST['employee'].'<td></tr>
         
         <tr><td>You’re Name</td><td>'.$_REQUEST['cname1'].'<td></tr>
         
         <tr><td>You’re Phone number</td><td>'.$_REQUEST['phnumber'].'<td></tr>
		 
		 <tr><td>Name of Current Employer</td><td>'.$_REQUEST['currentname'].'<td></tr>
         
         <tr><td>You’re Email</td><td>'.$_REQUEST['cemail2'].'<td></tr> -->





